apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-routr-connect-hpa
  namespace: {{ .Release.Namespace }}  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-routr-connect
  minReplicas: {{ .Values.connect.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.connect.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.connect.autoscaling.targetCPUUtilizationPercentage }}
