apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-connect
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
    service: connect
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
      service: connect
  template:
    metadata:
      annotations: 
      {{- with .Values.connect.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
        service: connect
    spec:
      securityContext:
        runAsUser: {{ .Values.connect.securityContext.runAsUser }}
        runAsGroup: {{ .Values.connect.securityContext.runAsGroup }}
        fsGroup: {{ .Values.connect.securityContext.fsGroup }}
      containers:
        - name: connect
          image: "{{ .Values.connect.image.repository }}:{{ .Values.connect.image.tag }}"
          imagePullPolicy: {{ .Values.connect.image.pullPolicy }}
          livenessProbe:
            exec:
              command: ["healthcheck"]
            initialDelaySeconds: {{ .Values.connect.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.connect.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.connect.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.connect.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.connect.livenessProbe.timeoutSeconds }}          
          env:
            - name: LOCATION_ADDR
              value: {{ .Release.Name }}-routr-location.{{ .Release.Namespace }}:51902
            - name: API_ADDR
              value: {{ .Release.Name }}-routr-apiserver.{{ .Release.Namespace }}:51907
            - name: LOGS_LEVEL
              value: {{ .Values.global.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.otlExporter }}
          ports:
            - containerPort: 51904
          resources:
            {{- if .Values.connect.resources.limits }}
            limits:
            {{- .Values.connect.resources.limits | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.connect.resources.requests }}
            requests:
            {{- .Values.connect.resources.requests | toYaml | nindent 12 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.connect.securityContext.allowPrivilegeEscalation }}
