apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-routr-connect
  namespace: {{ .Release.Namespace }}  
  labels:
    app: routr
    service: connect
spec:
  ports:
  - port: 51904
    targetPort: 51904
  selector:
    app: routr
    service: connect
