apiVersion: v2
name: routr-connect
description: Routr Connect Helm Chart
type: application
version: 0.1.0
appVersion: 2.0.8-alpha.30
dependencies:
  - name: routr-core
    version: 0.1.0
    repository: file://../core
  - name: postgresql
    version: 12.1.15
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.7.3
    repository: https://charts.bitnami.com/bitnami
