global:
  routr:
    logsLevel: verbose
    otlExporter: http://jaeger:14268/api/traces
  postgresql:
    auth:
      username: routr
      password: changeit

postgresql:
  enabled: true
  auth:
    username: routr
    password: changeit

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

# Connect Service defaults
rtprelay:
  rtpeHost: ""
  rtpPort: 22222
  image: 
    repository: fonoster/routr-rtprelay
    tag: latest
    pullPolicy: IfNotPresent
  podAnnotations: {}
  serviceAnnotations: {}    
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    allowPrivilegeEscalation: false
  resources:
    limits: {}
    requests: {}
  autoscaling:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

# Connect Service defaults
apiserver:
  image: 
    repository: fonoster/routr-pgdata
    tag: latest
    pullPolicy: IfNotPresent
  podAnnotations: {}
  serviceAnnotations: {}    
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    allowPrivilegeEscalation: false
  resources:
    limits: {}
    requests: {}
  autoscaling:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

# Connect Service defaults
connect:
  image: 
    repository: fonoster/routr-connect
    tag: latest
    pullPolicy: IfNotPresent
  podAnnotations: {}
  serviceAnnotations: {}    
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    allowPrivilegeEscalation: false
  resources:
    limits: {}
    requests: {}
  autoscaling:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

# APIServer Service defaults
registry:
  registerInterval: 20
  cache: 
    provider: memory
    parameters: ""
  methods:
    - INVITE
    - MESSAGE 
  image:
    repository: fonoster/routr-registry
    tag: latest
    pullPolicy: IfNotPresent
  podAnnotations: {}
  serviceAnnotations: {}    
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    allowPrivilegeEscalation: false
  resources:
    limits: {}
    requests: {}
  autoscaling:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
