version: '3.7'

services:

  #
  # End-to-end test for SIPConnect v1.1 support
  # docker-compose -f compliance.yml up --abort-on-container-exit --exit-code-from compliance
  #
  compliance:
    image: fonoster/seet:latest
    volumes:
      - ./mods/connect/etc/seet.json:/seet.json
      - ./mods/connect/etc/scenarios:/scenarios
