version: '3.7'

services:

  edgeport01:
    build: ./mods/edgeport
    image: fonoster/edgeport
    environment:
      CONFIG_PATH: /etc/routr/edgeport.json
      LOG4J2: /etc/routr/log4j2.yml
      LOGS_LEVEL: verbose
    ports:
      - 5060:5060
      - 5060:5060/udp
      - 5061:5061
      - 5062:5061
      - 5063:5061
    volumes:
      - ./config/log4j2.yml:/etc/routr/log4j2.yml
      - ./config/edgeport.json:/etc/routr/edgeport.json
      - ./etc/certs/domains-cert.jks:/etc/routr/domains-cert.jks

  edgeport02:
    build: ./mods/edgeport
    image: fonoster/edgeport
    environment:
      EDGEPORT_REF: ep002
      CONFIG_PATH: /etc/routr/edgeport.json
      LOG4J2: /etc/routr/log4j2.yml
      LOGS_LEVEL: verbose
    ports:
      - 6060:6060
      - 6060:6060/udp
      - 6061:6061
      - 6062:6061
      - 6063:6061
    volumes:
      - ./config/log4j2.yml:/etc/routr/log4j2.yml
      - ./config/edgeport.alt.json:/etc/routr/edgeport.json
      - ./etc/certs/domains-cert.jks:/etc/routr/domains-cert.jks

  dispatcher:
    build: ./mods/dispatcher
    image: fonoster/dispatcher
    environment:
      CONFIG_PATH: '/etc/routr/dispatcher.json'
      LOGS_LEVEL: verbose
    expose:
      - 51901
    volumes:
      - ./config/dispatcher.json:/etc/routr/dispatcher.json

  location:
    build: ./mods/location
    image: fonoster/location
    environment:
      CONFIG_PATH: '/etc/routr/location.json'
      LOGS_LEVEL: verbose
    expose:
      - 51902
    volumes:
      - ./config/location.json:/etc/routr/location.json

  # Connect processor
  connect:
    build: ./mods/connect
    image: fonoster/connect
    environment:
      LOCATION_ADDR: location:51902
      LOGS_LEVEL: verbose
    expose:
      - 51904

  # Use the auth.json file to add or remove agents
  simpleauth:
    build: ./mods/simpleauth
    image: fonoster/simpleauth
    environment:
      # Comma separated list of agents that are allowed to skip authentication
      WHITELIST: someuser01,someuser02
      PATH_TO_AUTH: '/etc/routr/auth.json'
      LOGS_LEVEL: verbose
    expose:
      - 51903
    volumes:
      - ./config/auth.json:/etc/routr/auth.json

  # Echo processor
  echo:
    build: ./mods/echo
    image: fonoster/echo
    environment:
      LOGS_LEVEL: verbose
    expose:
      - 51904

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.30.0
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250"
