version: "3.7"

services:

  # Main EdgePort server
  edgeport01:
    container_name: edgeport01
    image: fonoster/edgeport
    build: ./mods/edgeport
    environment:
      CONFIG_PATH: /etc/routr/edgeport.json
      LOG4J2: /etc/routr/log4j2.yml
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    ports:
      - 5060:5060
      - 5060:5060/udp
      - 5061:5061
      - 5062:5062
      - 5063:5063
    volumes:
      - ./config/log4j2.yml:/etc/routr/log4j2.yml
      - ./config/edgeport.json:/etc/routr/edgeport.json
      - ./etc/certs/domains-cert.jks:/etc/routr/domains-cert.jks
    networks:
      public: 
        ipv4_address: 10.111.220.2
      internal:
        ipv4_address: 10.111.221.2
        aliases:
          - sip01.edgeport.net

  # Secondary EdgePort server
  edgeport02:
    container_name: edgeport02
    image: fonoster/edgeport
    build: ./mods/edgeport
    environment:
      CONFIG_PATH: /etc/routr/edgeport.json
      LOG4J2: /etc/routr/log4j2.yml
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    ports:
      - 6060:6060
      - 6060:6060/udp
      - 6061:6061
      - 6062:6062
      - 6063:6063
    volumes:
      - ./config/log4j2.yml:/etc/routr/log4j2.yml
      - ./config/edgeport.alt.json:/etc/routr/edgeport.json
      - ./etc/certs/domains-cert.jks:/etc/routr/domains-cert.jks
    networks:
      public: 
        ipv4_address: 10.111.220.3
      internal:
        ipv4_address: 10.111.221.3
        aliases:
          - sip02.edgeport.net        

  # Takes care of routing traffic from the EdgePort servers
  dispatcher:
    container_name: dispatcher
    image: fonoster/dispatcher
    build: ./mods/dispatcher
    environment:
      CONFIG_PATH: /etc/routr/dispatcher.json
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51901
    volumes:
      - ./config/dispatcher.json:/etc/routr/dispatcher.json
    networks:
      internal:
        ipv4_address: 10.111.221.4

  # Store the location to all SIP endpoints in the network
  location:
    container_name: location
    image: fonoster/location
    build: ./mods/location
    environment:
      CONFIG_PATH: /etc/routr/location.json
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51902
    volumes:
      - ./config/location.json:/etc/routr/location.json
    networks:
      internal:
        ipv4_address: 10.111.221.5

  # Connect processor
  connect:
    container_name: connect
    image: fonoster/connect
    build: ./mods/connect
    environment:
      LOCATION_ADDR: location:51902
      API_ADDR: simpledata:51907
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51904
    networks:
      internal:
        ipv4_address: 10.111.221.6

  # Simple data API
  simpledata:
    container_name: simpledata
    image: fonoster/simpledata
    build: ./mods/simpledata
    environment:
      PATH_TO_SCHEMAS: /etc/routr/schemas
      PATH_TO_RESOURCES: /etc/routr/resources
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51907
    volumes:
      - ./mods/simpledata/etc/schemas/:/etc/routr/schemas
      - ./config/resources:/etc/routr/resources
    networks:
      internal:
        ipv4_address: 10.111.221.8

  # Takes gRPC requests and sends them to an EdgePort
  requester:
    container_name: requester
    image: fonoster/requester
    build: ./mods/requester
    environment:
      LOG4J2: /etc/routr/log4j2.yml
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51909
    volumes:
      - ./config/log4j2.yml:/etc/routr/log4j2.yml
    networks:
      internal:
        ipv4_address: 10.111.221.9

  # Sends registration request on behalf of trunks
  registry:
    container_name: registry
    image: fonoster/registry
    build: ./mods/registry
    environment:
      CONFIG_PATH: /etc/routr/registry.json
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51910
    volumes:
      - ./config/registry.json:/etc/routr/registry.json
    networks:
      internal:
        ipv4_address: 10.111.221.10

  # Tracing monitoring
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.30.0
    ports:
      - 16686:16686
      - 14268:14268
      - 14250:14250
    networks:
      internal:
        ipv4_address: 10.111.221.12

  #
  # SIP End to End Test (SEET) compliance test for SIPConnect v1.1 support
  # docker-compose up --abort-on-container-exit --exit-code-from compliance
  #
  compliance:
    container_name: compliance
    image: fonoster/seet
    depends_on: 
      - edgeport01
      - edgeport02
      - dispatcher
      - registry
      - requester
      - simpledata
      - connect
    environment:
      SCENARIOS: /seet.json
    ports:
      - 7060:7060/udp
    volumes:
      - ./mods/connect/etc/seet.json/:/seet.json
      - ./mods/connect/etc/scenarios:/scenarios
    networks:
      internal:
        ipv4_address: 10.111.221.22
        aliases:
          - sip.provider.net

networks:
  public:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.111.220.1/24
  internal:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.111.221.1/24
