version: '3.7'

services:

  edgeport01:
    container_name: edgeport01
    image: fonoster/edgeport
    build: ./mods/edgeport
    environment:
      CONFIG_PATH: /etc/routr/edgeport.json
      LOG4J2: /etc/routr/log4j2.yml
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
    ports:
      - 5060:5060
      - 5060:5060/udp
      - 5061:5061
      - 5062:5062
      - 5063:5063
    volumes:
      - ./config/log4j2.yml:/etc/routr/log4j2.yml
      - ./config/edgeport.json:/etc/routr/edgeport.json
      - ./etc/certs/domains-cert.jks:/etc/routr/domains-cert.jks

  edgeport02:
    container_name: edgeport02
    image: fonoster/edgeport
    build: ./mods/edgeport
    environment:
      CONFIG_PATH: /etc/routr/edgeport.json
      LOG4J2: /etc/routr/log4j2.yml
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
    ports:
      - 6060:6060
      - 6060:6060/udp
      - 6061:6061
      - 6062:6062
      - 6063:6063
    volumes:
      - ./config/log4j2.yml:/etc/routr/log4j2.yml
      - ./config/edgeport.alt.json:/etc/routr/edgeport.json
      - ./etc/certs/domains-cert.jks:/etc/routr/domains-cert.jks

  dispatcher:
    container_name: dispatcher
    image: fonoster/dispatcher
    build: ./mods/dispatcher
    environment:
      CONFIG_PATH: /etc/routr/dispatcher.json
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51901
    volumes:
      - ./config/dispatcher.json:/etc/routr/dispatcher.json

  location:
    container_name: location
    image: fonoster/location
    build: ./mods/location
    environment:
      CONFIG_PATH: /etc/routr/location.json
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51902
    volumes:
      - ./config/location.json:/etc/routr/location.json

  # Connect processor
  connect:
    container_name: connect
    image: fonoster/connect
    build: ./mods/connect
    environment:
      LOCATION_ADDR: location:51902
      API_ADDR: simpledata:52901
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    ports:
      - 51904:51904
    expose:
      - 51904

  # Use the auth.json file to add or remove agents
  simpleauth:
    container_name: simpleauth
    image: fonoster/simpleauth
    build: ./mods/simpleauth
    environment:
      # Comma separated list of agents that are allowed to skip authentication
      WHITELIST: pbx-1
      PATH_TO_AUTH: /etc/routr/auth.json
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 51903
    volumes:
      - ./config/auth.json:/etc/routr/auth.json

  # Simple data API
  simpledata:
    container_name: simpledata
    image: fonoster/simpledata
    build: ./mods/simpledata
    environment:
      PATH_TO_SCHEMAS: /etc/routr/schemas
      PATH_TO_RESOURCES: /etc/routr/resources
      LOGS_LEVEL: verbose
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    expose:
      - 52901
    volumes:
      - ./mods/simpledata/etc/schemas/:/etc/routr/schemas
      - ./config/resources:/etc/routr/resources

  # Echo processor
  echo:
    container_name: echo
    image: fonoster/echo
    build: ./mods/echo
    environment:
      LOGS_LEVEL: verbose
    expose:
      - 51904

  # Jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.30.0
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250"
