version: '3.7'

services:

  edgeport:
    build: ./mods/edgeport
    image: routr/edgeport
    environment:
      CONFIG_PATH: '/etc/routr/edgeport.json'
      LOG4J2: /etc/routr/log4j2.yml
      LOGS_LEVEL: verbose
    ports:
      - 5060:5060
      - 5060:5060/udp
      - 5061:5061
      - 5062:5061
      - 5063:5061
    volumes:
      - ./config/log4j2.xml:/etc/routr/log4j2.yml
      - ./config/edgeport.json:/etc/routr/edgeport.json

  dispatcher:
    build: ./mods/dispatcher
    image: routr/dispatcher
    environment:
      CONFIG_PATH: '/etc/routr/dispatcher.json'
      LOGS_LEVEL: verbose
    expose:
      - 51901
    volumes:
      - ./config/dispatcher.json:/etc/routr/dispatcher.json

  location:
    build: ./mods/location
    image: routr/location
    environment:
      CONFIG_PATH: '/etc/routr/location.json'
      LOGS_LEVEL: verbose
    expose:
      - 51902
    volumes:
      - ./config/location.json:/etc/routr/location.json

  # Connect processor
  connect:
    build: ./mods/connect
    image: routr/connect
    environment:
      LOGS_LEVEL: verbose
    expose:
      - 51904

  # Use the auth.json file to add or remove agents
  simpleauth:
    build: ./mods/simpleauth
    image: routr/simpleauth
    environment:
      CONFIG_PATH: '/etc/routr/auth.json'
      LOGS_LEVEL: verbose
    expose:
      - 51903
    volumes:
      - ./config/auth.json:/etc/routr/auth.json

  # Echo processor
  echo:
    build: ./mods/echo
    image: routr/echo
    environment:
      LOGS_LEVEL: verbose
    expose:
      - 51904
