apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-registry
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.registry.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/registry/configmaps.yaml") . | sha256sum }}    
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.registry.securityContext.runAsUser }}
        runAsGroup: {{ .Values.registry.securityContext.runAsGroup }}
        fsGroup: {{ .Values.registry.securityContext.fsGroup }}
      containers:
        - name: registry
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          imagePullPolicy: {{ .Values.registry.image.pullPolicy }}
          env:
            - name: CONFIG_PATH
              value: /etc/routr/registry.yaml
            - name: LOGS_LEVEL
              value: {{ .Values.global.routr.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.routr.otlExporter }}
          ports:
            - containerPort: 51901
          volumeMounts:
            - name: config
              mountPath: /etc/routr/registry.yaml
              subPath: registry.yaml
          resources:
            {{- if .Values.registry.resources.limits }}
            limits:
            {{- .Values.registry.resources.limits | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.registry.resources.requests }}
            requests:
            {{- .Values.registry.resources.requests | toYaml | nindent 12 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.registry.securityContext.allowPrivilegeEscalation }}           
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-routr-registry-config
