apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-apiserver
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: 
      {{- with .Values.apiserver.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.apiserver.securityContext.runAsUser }}
        runAsGroup: {{ .Values.apiserver.securityContext.runAsGroup }}
        fsGroup: {{ .Values.apiserver.securityContext.fsGroup }}
      containers:
        - name: apiserver
          image: "{{ .Values.apiserver.image.repository }}:{{ .Values.apiserver.image.tag }}"
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: postgresql://routr:changeit@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}:5432/routr?schema=public
            - name: LOGS_LEVEL
              value: {{ .Values.global.routr.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.routr.otlExporter }}
          ports:
            - containerPort: 51907
          resources:
            {{- if .Values.apiserver.resources.limits }}
            limits:
            {{- .Values.apiserver.resources.limits | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.apiserver.resources.requests }}
            requests:
            {{- .Values.apiserver.resources.requests | toYaml | nindent 12 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.apiserver.securityContext.allowPrivilegeEscalation }}
