apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-apiserver
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
    service: apiserver
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
      service: apiserver
  template:
    metadata:
      annotations: 
      {{- with .Values.apiserver.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
        service: apiserver
    spec:
      securityContext:
        runAsUser: {{ .Values.apiserver.securityContext.runAsUser }}
        runAsGroup: {{ .Values.apiserver.securityContext.runAsGroup }}
        fsGroup: {{ .Values.apiserver.securityContext.fsGroup }}
      containers:
        - name: apiserver
          image: "{{ .Values.apiserver.image.repository }}:{{ .Values.apiserver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          livenessProbe:
            exec:
              command: ["healthcheck"]
            initialDelaySeconds: {{ .Values.apiserver.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.apiserver.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.apiserver.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.apiserver.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.apiserver.livenessProbe.timeoutSeconds }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-routr-database-url
          env:
            - name: LOGS_LEVEL
              value: {{ .Values.global.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.otlExporter }}
          ports:
            - containerPort: 51907
          resources:
            {{- if .Values.apiserver.resources.limits }}
            limits:
            {{- .Values.apiserver.resources.limits | toYaml | nindent 14 }}
            {{- end }}
            {{- if .Values.apiserver.resources.requests }}
            requests:
            {{- .Values.apiserver.resources.requests | toYaml | nindent 14 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.apiserver.securityContext.allowPrivilegeEscalation }}
