apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-routr-database-url
  namespace: {{ .Release.Namespace }}  
type: Opaque
stringData:
  {{- if .Values.apiserver.databaseUrl }}
  DATABASE_URL: {{ .Values.apiserver.databaseUrl }}
  {{- else }}  
  DATABASE_URL: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}:5432/routr?schema=public
  {{- end }}
