apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-routr-apiserver
  namespace: {{ .Release.Namespace }}
  {{- with .Values.apiserver.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
    service: apiserver
spec:
  ports:
  - port: 51907
    targetPort: 51907
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
    service: apiserver