apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-routr-apiserver
  namespace: {{ .Release.Namespace }}  
  labels:
    app: routr
    service: apiserver
spec:
  ports:
  - port: 51907
    targetPort: 51907
  selector:
    app: routr
    service: apiserver
