apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-routr-dispatcher-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
data:
  dispatcher.yaml: |-
    kind: MessageDispatcher
    apiVersion: v2draft1
    ref: message-dispatcher
    spec:
      bindAddr: 0.0.0.0:51901
      processors:
        - ref: connect-processor
          addr: {{ .Release.Name }}-routr-connect.{{ .Release.Namespace }}:51904
          matchFunc: req => true
          methods:
            - REGISTER
            - INVITE
            - ACK
            - BYE
            - CANCEL
