apiVersion: v1
kind: ConfigMap
metadata:
  name: voipnet-routr-edgeport-config
  namespace: default
data:
  edgeport.yaml: |-
    kind: EdgePort
    apiVersion: v2draft1
    ref: edge-port-01
    metadata:
      region: us-east1
    spec:
      unknownMethodAction: Discard
      processor:
        addr: voipnet-routr-dispatcher.default:51901  
      # securityContext:
      #   client:
      #     protocols:
      #       - SSLv3
      #       - TLSv1.2
      #     authType: DisabledAll
      #   keyStorePassword: changeit
      #   trustStorePassword: changeit
      #   keyStore: "/etc/routr/domains-cert.jks"
      #   trustStore: "/etc/routr/domains-cert.jks"
      #   keyStoreType: pkcs12
      externalAddrs:
        - 192.168.1.3
      localnets:
        - 192.168.1.3
      methods:
        - REGISTER
        - MESSAGE
        - INVITE
        - ACK
        - BYE
        - CANCEL
      transport:
        - protocol: tcp
          port: 5060
        - protocol: udp
          port: 5060
        # - protocol: tls
        #   port: 5061
        - protocol: ws 
          port: 5062
        # - protocol: wss
        #   port: 5063

  log4j2.yaml: |-
    Configuration:
      Appenders:
        Console:
          PatternLayout:
            pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-4level{lowerCase=true}]: (${sys:serviceName}) %c{1}.java %msg%n"
          name: Console
          target: SYSTEM_OUT
        RollingFile:
          - name: LogToRollingFile
            fileName: logs/routr.log
            filePattern: "logs/routr-%d{MM-dd-yyyy}-%i.log.gz"
            PatternLayout:
              pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-4level{lowerCase=true}]: (${sys:serviceName}) %c{1}.java %msg%n"
            Policies:
              SizeBasedTriggeringPolicy:
                size: 10MB
            DefaultRollOverStrategy:
              max: 10
      Loggers:
        Logger:
          - name: io.routr
            level: debug
            AppenderRef:
              - ref: Console
              - ref: LogToRollingFile
        Root:
          level: error
          AppenderRef:
            - ref: LogToRollingFile