apiVersion: v1
kind: Service
metadata:
  name: voipnet-routr-edgeport
  labels:
    app: routr-edgeport
spec:
  ports:
  - name: siptcp
    port: 5060
    targetPort: 5060
    protocol: TCP
  - name: sipudp
    port: 5060
    targetPort: 5060
    protocol: UDP    
  selector:
    app: routr-edgeport