Configuration:
  Appenders:
    Console:
      PatternLayout:
        pattern: '%highlight{%-4level{lowerCase=true}}: %msg%n'
      name: Console
      target: SYSTEM_OUT
    # Do not remove this appender as is needed by the /system/logs endpoint
    # If you want to save the logs elsewhere just add another appender.
    RollingFile:
      - name: LogToRollingFile
        fileName: logs/routr.log
        filePattern: "${sys:DATA}/logs/$${date:yyyy-MM}/routr-%d{MM-dd-yyyy}-%i.log.gz"
        PatternLayout:
          pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 10MB
        DefaultRollOverStrategy:
          max: 10
  Loggers:
    Logger:
      - name: io.routr
        level: info
        AppenderRef:
        - ref: Console
        - ref: LogToRollingFile

    Root:
      level: error
      AppenderRef:
      - ref: LogToRollingFile
