Configuration:
  Appenders:
    Console:
      PatternLayout:
        pattern: '%highlight{%-4level{lowerCase=true}}: %msg%n'
      name: Console
      target: SYSTEM_OUT
    RollingFile:
      - name: LogToRollingFile
        fileName: logs/routr.log
        filePattern: "logs/routr-%d{MM-dd-yyyy}-%i.log.gz"
        PatternLayout:
          pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 10MB
        DefaultRollOverStrategy:
          max: 10
  Loggers:
    Logger:
      - name: io.routr
        level: debug
        AppenderRef:
          - ref: Console
          - ref: LogToRollingFile

    Root:
      level: error
      AppenderRef:
        - ref: LogToRollingFile
