apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-routr-location-config
  namespace: {{ .Release.Namespace }}
data:
  location.yaml: |-
    kind: Location
    apiVersion: v2draft1
    metadata:
      region: us-east1
    spec:
      bindAddr: 0.0.0.0:51902
      cache:
        provider: memory
        # provider: redis
        # parameters: host={{ .Release.Name }}-redis-master.default,port=6379
