apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-location
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.location.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/location/configmaps.yaml") . | sha256sum }}      
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.location.securityContext.runAsUser }}
        runAsGroup: {{ .Values.location.securityContext.runAsGroup }}
        fsGroup: {{ .Values.location.securityContext.fsGroup }}
      containers:
        - name: location
          image: "{{ .Values.location.image.repository }}:{{ .Values.dispatcher.image.tag }}"
          imagePullPolicy: {{ .Values.location.image.pullPolicy }}
          env:
            - name: CONFIG_PATH
              value: /etc/routr/location.yaml
            - name: LOGS_LEVEL
              value: {{ .Values.global.routr.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.routr.otlExporter }}
          ports:
            - containerPort: 51902
          volumeMounts:
            - name: config
              mountPath: /etc/routr/location.yaml
              subPath: location.yaml
          resources:
            {{- if .Values.dispatcher.resources.limits }}
            limits:
            {{- .Values.dispatcher.resources.limits | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.dispatcher.resources.requests }}
            requests:
            {{- .Values.dispatcher.resources.requests | toYaml | nindent 12 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.location.securityContext.allowPrivilegeEscalation }}          
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-routr-location-config
