apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-routr-location
  namespace: {{ .Release.Namespace }}  
  labels:
    app: routr
    service: location
spec:
  ports:
  - port: 51902
    targetPort: 51902
  selector:
    app: routr
    service: location