- apiVersion: v2draft1
  kind: Credentials
  ref: credentials-01
  metadata:
    name: Agent Credentials
  spec:
    credentials:
      username: "1001"
      password: "1234"
- apiVersion: v2draft1
  kind: Credentials
  ref: credentials-02
  metadata:
    name: Agent Credentials
  spec:
    credentials:
      username: "1002"
      password: "1234"
- apiVersion: v2draft1
  kind: Credentials
  ref: credentials-03
  metadata:
    name: Peer Credentials
  spec:
    credentials:
      username: asterisk
      password: "1234"
- apiVersion: v2draft1
  kind: Credentials
  ref: credentials-04
  metadata:
    name: Trunk Credentials
  spec:
    credentials:
      username: pbx-1
      password: "1234"
- apiVersion: v2draft1
  kind: Credentials
  ref: credentials-05
  metadata:
    name: Peer Credentials
  spec:
    credentials:
      username: freeswitch
      password: "1234"
