- apiVersion: v2draft1
  kind: Trunk
  ref: trunk-01
  metadata:
    name: Test Trunk
    region: us-east1
  spec:
    inbound:
      uri: trunk01.acme.com
      accessControlListRef: acl-01
    outbound:
      sendRegister: true
      credentialsRef: credentials-04
      uris:
        - uri:
            user: pbx-1
            host: sip.provider.net
            port: 7060
            transport: udp
          priority: 10
          weight: 10
          enabled: true

- apiVersion: v2draft1
  kind: Trunk
  ref: trunk-02
  metadata:
    name: Test Trunk2
    region: us-east1
  spec:
    inbound:
      uri: trunk02.acme.com
      accessControlListRef: acl-01
      credentialsRef: credentials-04
    outbound:
      credentialsRef: credentials-04
      uris:
        - uri:
            user: pbx-1
            host: sip.provider.net
            port: 7060
            transport: udp
          priority: 10
          weight: 10
          enabled: true

- apiVersion: v2draft1
  kind: Trunk
  ref: trunk-03
  metadata:
    name: Test Trunk3
    region: us-west1
  spec:
    inbound:
      uri: trunk03.acme.com
      credentialsRef: credentials-04
    outbound:
      credentialsRef: credentials-04
      uris:
        - uri:
            user: pbx-1
            host: sip.provider.net
            port: 7060
            transport: udp
          priority: 10
          weight: 10
          enabled: true
