{{- if eq .Values.udpSignalingService.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}-{{ .Values.udpSignalingService.name }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.udpSignalingService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  {{- if .Values.udpSignalingService.externalIPs }}
  externalIPs: 
  {{- range .Values.udpSignalingService.externalIPs }}
    - {{.}}
  {{- end }}
  {{- end }}
  type: {{ .Values.udpSignalingService.type }}
  {{- if ne .Values.udpSignalingService.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.udpSignalingService.externalTrafficPolicy }}
  {{- end}}
  ports:
  - name: {{ .Values.udpSignalingService.name }}
    port: {{ .Values.udpSignalingService.port }}
    protocol: UDP
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if eq .Values.tcpSignalingService.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}-{{ .Values.tcpSignalingService.name }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.tcpSignalingService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  {{- if .Values.tcpSignalingService.externalIPs }}
  externalIPs: 
  {{- range .Values.tcpSignalingService.externalIPs }}
    - {{.}}
  {{- end }}
  {{- end }}
  type: {{ .Values.tcpSignalingService.type }}
  {{- if ne .Values.tcpSignalingService.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.tcpSignalingService.externalTrafficPolicy }}
  {{- end}}
  ports:
  {{- range .Values.tcpSignalingService.ports }}
  - name: {{ .name }}
    port: {{ .port }}
  {{- end }}
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
{{- end }}