name: publish docs to github pages (v2)

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'ops/**'
    branches:
      - main

jobs:
  deployment:
    name: Build & Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install docs dependencies
        run: |
          pip install --upgrade pip
          pip install -Iv mkdocs==1.0.4
          pip install -Iv pymdown-extensions==6.0
          pip install -Iv mkdocs-material==4.4.0
      - name: Package charts
        run: |
          helm package ops/charts/connect -d .charts
          helm repo index .charts
      - name: Build sources
        run: |
          mkdocs build
          mkdir -p out/docs
          mv site/* out/docs
          mv docs/CNAME out
          mv docs/site_assets out
          mv docs/index.html out
          mv .charts out/charts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
