name: sip-connect v1.1
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - 'docs/**'
    branches:
    - v2
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Build project
        run: npm run make
      - name: Compliance tests
        run: |
          docker-compose up --abort-on-container-exit --exit-code-from compliance
