name: sip-connect v1.1
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - main
jobs:
  build-and-test:
    name: Build and run SIP Connect Compliance Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Build project
        run: npm run make
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: routr-build
          path: |
            mods
            lerna.json
            !mods/**/node_modules
            !mods/src
            !mods/test
            !mods/**/dist/*.ts
      - name: Compliance tests
        run: |
          docker-compose up --build --abort-on-container-exit --exit-code-from compliance

  publish-to-docker-hub:
    name: Publish to Docker Hub
    uses: ./.github/workflows/docker-hub-release.yml
    secrets: inherit
    needs: [build-and-test]
