name: release (v2)
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - main
jobs:
  build-and-test:
    name: Build and run SIP Connect Compliance Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Build project
        run: npm run make
      - name: Check for next release
        run: |
          release=$(.scripts/next-release.sh)
          echo "Next release: $release"
          echo "RELEASE=$release" >> $GITHUB_ENV
      - name: Publish packages to NPM
        if: env.RELEASE != 'none'
        run: |
          echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
          echo "@routr:registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout package-lock.json

          npm run publish
      - name: Create release note
        if: env.RELEASE != 'none'
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore
          config_file: ./tag-changelog-config.js
      - name: Create draft release
        if: env.RELEASE != 'none'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: routr-build
          path: |
            mods
            .scripts
            config
            lerna.json
            Dockerfile
            !mods/**/node_modules
            !mods/**/src
            !mods/**/test
            !mods/**/dist/*.ts
      - name: SIP Connect v1.1 Compliance Tests
        run: |
          docker-compose up --build --abort-on-container-exit --exit-code-from compliance

  publish-to-docker-hub:
    name: Publish to Docker Hub
    uses: ./.github/workflows/docker-hub-release.yml
    secrets: inherit
    needs: [build-and-test]
