apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-requester
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.requester.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/requester/configmaps.yaml") . | sha256sum }}      
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.requester.securityContext.runAsUser }}
        runAsGroup: {{ .Values.requester.securityContext.runAsGroup }}
        fsGroup: {{ .Values.requester.securityContext.fsGroup }}
      containers:
        - name: requester
          image: "{{ .Values.requester.image.repository }}:{{ .Values.requester.image.tag }}"
          imagePullPolicy: {{ .Values.requester.image.pullPolicy }}
          env:
            - name: LOGS_LEVEL
              value: {{ .Values.global.routr.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.routr.otlExporter }}
          ports:
            - containerPort: 51909
          volumeMounts:
            - name: config
              mountPath: /etc/routr/log4j2.yaml
              subPath: log4j2.yaml
          resources:
            {{- if .Values.dispatcher.resources.limits }}
            limits:
            {{- .Values.dispatcher.resources.limits | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.dispatcher.resources.requests }}
            requests:
            {{- .Values.dispatcher.resources.requests | toYaml | nindent 12 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.requester.securityContext.allowPrivilegeEscalation }}         
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-routr-requester-config
