apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-routr-dispatcher-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
data:
  dispatcher.yaml: |-
    kind: MessageDispatcher
    apiVersion: v2draft1
    ref: message-dispatcher
    spec:
      bindAddr: 0.0.0.0:51901
      processors:
        {{- range .Values.dispatcher.processors }}
        - ref: {{ .ref }}
          addr: {{ .servicePrefix | default $.Release.Name }}-{{ .serviceName }}.{{ .serviceNamespace | default $.Release.Namespace }}:51904
          matchFunc: {{ .matchFunc | quote }}
          methods:
          {{- range .methods }}
            - {{ . }}
          {{- end }}
        {{- end }}
      {{- if .Values.dispatcher.middlewares }}
      middlewares:
        {{- range .Values.dispatcher.middlewares }}
        - ref: {{ .ref }}
          addr: {{ .servicePrefix | default $.Release.Name }}-{{ .serviceName }}.{{ .serviceNamespace | default $.Release.Namespace }}:51903
          postProcessor: {{ .postProcessor }}
        {{- end }}
      {{- end }}
